### PR TITLE
comments on Intermediate Git

### PR DESCRIPTION
**Pull request by dutc**
PR including all comments and thoughts on _Intermediate Git_.

### CODE REVIEW

**Comment by dutc** [comment]
Overall:

**Who is the intended audience? `matplotlib` contributors? Programmers? Scientists?**

- What is the “angle” or “hook” here? Why is someone bothering to read this?†
- Are they expected to know what a DAG is (and care?)
- Are they expected to know what a Merkle tree is (and care)?
- Are they expected to know what a content-addressible store is (and care?) (Should you mention this? Does/doesn't this aspect matter more than that it's a Merkle tree?)

† e.g., how the core dev of a major project (with 100000 commits & 100 years of history) has come to terms with `git`

**What does it matter…?**

- Why does it matter that you can validate each commit independently and the full repository?
- Why does it matter that `git` stores the snapshot (not the delta)? (Would a clearer distinction in terminology help, rather than saying “creating a copy”?)
- That there is one canonical repository? (Will they care about how this ties into code distribution, development collaboration, and private forking mechanisms?†)
- That each clone is a complete copy of the repository & its associated history? (Does anyone care about the “I want to develop code on my international flights without wifi” use-case anymore?)

† Is the a canonical Linux repository really `/torvalds/linux`? Who does this matter to? Why?

**I like…**

- The listing of “what would we want to do to [the graph]”; could you put a quick hint for how these map to `git` operations? (e.g., “give commits human readable names (i.e., `git tag`)”)
- Breaking down the symbol “pull request” into what it actually means—“I request you pull from my fork.”

**Comment by dutc** [comment]
> In this view when you are collectively working on code managed with git there
> is only one global graph which is the history.  Any given computer contains
> only a sub-graph of the global graph and each person participating in the
> development has a set of flags they can move around the graph.

Should you distinguish this from the idea that each `git clone` is a complete history? Does anyone actually do shallow clones for anything other than building?

**Comment by dutc** [comment]
> You should always create "annotated" tags.

What is the distinction between annotated and lightweight tags, and why should we never do the latter?

> 
> There is a "dual space" relationship between the code state at each commit and
> the differences between the commits.  If you have one you can always compute
> the other. On first glance the natural way to track the changes of source over
> time is to track the differences (this is in fact how many earlier version
> control systems worked!).  However git (and mercurial) instead track the full
> state of the of the source at each commit which solves a number of performance
> problems and enables some additional operations.

Does it matter that packfiles are delta-based? What is the implication of the canonical storage being blobs not deltas?

> sub-command.  To get the difference between two commits:
> ```sh
> git diff <commitA> <commitB>
> ```

What is the order of this? (I get this wrong all the time.) Can you label this `$from_commit` and `$to_commit`?

**Comment by dutc** [comment]
> In addition, there is also a new `git switch` [sub-command](https://git-scm.com/docs/git-switch) that is specifically for switching branches.

Do you want to talk about detached head mode (which I imagine comes up a lot)?

> As you make changes there are two common commands `git status`
> [sub-command](https://git-scm.com/docs/git-status) and `git diff`
> [sub-command](https://git-scm.com/docs/git-diff).  `git status` will give you a
> summary of what changes you have in the local tree, relative to `HEAD` and what
> changes are staged. `git diff`, when called with no arguments will show the detailed
> diff between the current working tree and `HEAD`.

Do you want to go through the differences between the working tree, staging area, and repository (and what the index is)?

This SO answer has some decent images: https://stackoverflow.com/questions/3689838/whats-the-difference-between-head-working-tree-and-index-in-git

**Comment by dutc** [comment]
> If you want to move a range of commits from one place to another you can use
> the `git rebase` [sub-command](https://git-scm.com/docs/git-rebase).

Might it be helpful to discuss the difference in what the history represents?
- Is it the physical history of events (in which case, you might preserve exact history, including “typo” commits)?
- Is it the logical history transitioning between working states (in which case, you might ask people to rebase in PRs)?

These two approaches are, presumably, tied to what `git` is being used for, which is dependent on the project and workflow.

**Comment by dutc** [comment]
> ## Other things you might want to do
> - set up multiple worktrees

I am a big fan of `git worktree` for my work. If you are, too, this might be good “pro tip”-style content that fits with the “how a major-project lead (or major project-lead) uses `git`” framing?

**Comment by tacaswell** [comment]
Thank you @dutc !  I am taken most of these and positively decided to not address others as "out of scope" (details about how staging actually works, how the packfiles work,

**Pull request merged**
